version: '2'
services:
  yo:
    image: crypticker
    container_name: crypticker_ticker
    shm_size: 512M
    cap_add:
      - SYS_ADMIN
    build:
      context: .
      dockerfile: Docketeer
    command: node puppeteer.js
    links:
      - crypticker_srv
    depends_on:
      - crypticker_srv
    # command: node -e "`cat puppeteer.js`"
  # crypticker_ticker:
  #   image: crypticker
  #   container_name: crypticker_ticker
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: cron && tail -f /var/log/cron.log
  #   links:
  #     - crypticker_srv
  #   depends_on:
  #     - crypticker_srv
  #   restart: always
  #   environment:
  #     - STDOUT_LOC=/proc/1/fd/1
  #     - STDERR_LOC=/proc/1/fd/2
  #     - WS_PORT=${WS_PORT}
  #     - WS_NAME='crypticker_srv'
  #   env_file:
  #     - .env

  crypticker_srv:
    image: crypticker
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: crypticker_srv
    command: node server.js
    links:
      - crypticker_db
    depends_on:
      - crypticker_db
    ports:
      - "127.0.0.1:${WS_HOST_PORT}:${WS_PORT}"
    environment:
      - WS_PORT=${WS_PORT}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=crypticker
      - MONGO_COLL=tickers
      - MONGO_SRV=crypticker_db
    env_file:
      - .env
    restart: always

  crypticker_db:
    container_name: crypticker_db
    image: mongo:latest
    ports:
      - "127.0.0.1:${MONGO_HOST_PORT}:${MONGO_PORT}"
    volumes:
      - /var/db/crypticker/mg:/data/db
    env_file:
      - .env
    restart: always

